language: cpp

matrix:
  include:
  - os: linux
    compiler: i686-w64-mingw32-g++
    env: EXTRA_CMAKE_FLAGS="-DCBLAS_LIBRARIES=/usr/lib/libblas.so -DBLAS_LIBRARIES=/usr/lib/libblas.so -DLAPACK_LIBRARIES=/usr/lib/liblapack.so -DCMAKE_TOOLCHAIN_FILE=../CMake/toolchain-i686-w64-mingw32.cmake" CMAKE_BUILD_TYPE=Release BUILD_SHARED_LIBS=ON

before_install:
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; brew tap homebrew/science; else sudo apt-get update -qq; fi
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install openblas; else sudo apt-get install -qq libblas-dev; fi
 - env
 - sudo apt-get install gcc-mingw-w64-i686 g++-mingw-w64-i686 binutils-mingw-w64-i686 

before_script:
  - mkdir build
  - cd build

script:
  - cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE $EXTRA_CMAKE_FLAGS ..
  - make VERBOSE=1
  - make test
